backend:
    name: git-gateway
    branch: master

media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
site_url: https://sinelanguage-ui.netlify.com
logo_url: https://sinelanguage-ui.netlify.com/images/logo.jpg

collections:
    - name: 'artist'
      extension: json
      label: 'Artist'
      folder: 'src/data'
      create: true
      filter: { field: 'layout', value: 'artist' }
      slug: '{{layout}}_{{slug}}'
      fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'artist' }
          - { label: 'Url', name: 'url', widget: 'hidden', default: 'artists/{{id}}' }
          - { label: 'Unique Id (No spaces)', name: 'id', widget: 'string' }
          - { label: 'Name', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'date' }
          - { label: 'Image', name: 'thumbnail', widget: 'image' }
          - { label: 'Biography', name: 'body', widget: 'markdown' }
    - name: 'release'
      extension: json
      label: 'Release'
      folder: 'src/data'
      create: true
      filter: { field: 'layout', value: 'release' }
      slug: '{{layout}}_{{slug}}'
      fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'release' }
          - { label: 'Url', name: 'url', widget: 'hidden', default: 'releases/{{id}}' }
          - {
                label: 'Catalog Number',
                hint: 'Use the format SINEXXX',
                name: 'id',
                widget: 'string',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'date' }
          - { label: 'Image', name: 'thumbnail', widget: 'image' }
    - name: 'podcast'
      extension: json
      label: 'Podcast'
      folder: 'src/data'
      create: true
      filter: { field: 'layout', value: 'podcast' }
      slug: '{{layout}}_{{slug}}'
      fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'podcast' }
          - { label: 'Url', name: 'url', widget: 'hidden', default: 'podcasts/{{id}}' }
          - { label: 'Catalog Number', hint: 'Use the format SLRXXX', name: 'id', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'date' }
          - { label: 'Image', name: 'thumbnail', widget: 'image' }
    - name: 'event'
      extension: json
      label: 'Event'
      folder: 'src/data'
      create: true
      filter: { field: 'layout', value: 'event' }
      slug: '{{layout}}_{{slug}}'
      fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'event' }
          - { label: 'Url', name: 'url', widget: 'hidden', default: 'events/{{id}}' }
          - { label: 'Id', name: 'id', widget: 'hidden', default: '{{date}}' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Date', name: 'date', widget: 'date', format: 'MMM Do YY' }
          - { label: 'Image', name: 'thumbnail', widget: 'image' }
