backend:
    name: git-gateway
    branch: master

media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
site_url: https://sinelanguage-ui.netlify.com
logo_url: https://sinelanguage-ui.netlify.com/images/logo.jpg

collections:
    - name: 'artist'
      extension: json
      label: 'Artist'
      folder: 'src/data'
      create: true
      filter: { field: 'layout', value: 'artist' }
      slug: '{{layout}}_{{slug}}'
      fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'artist' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'date' }
          - { label: 'Image', name: 'thumbnail', widget: 'image' }
          - { label: 'Biography', name: 'body', widget: 'markdown' }
    - name: 'podcast'
      extension: json
      label: 'Podcast'
      folder: 'src/data'
      create: true
      filter: { field: 'layout', value: 'podcast' }
      slug: '{{layout}}_{{slug}}'
      fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'podcast' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'date' }
          - { label: 'Image', name: 'thumbnail', widget: 'image' }
